version: '3.8'

services:
  db:
    image: postgres:15
    container_name: varta_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Varta.Store.API/Dockerfile
    container_name: varta_api
    restart: always
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      Authentication__Steam__ApplicationKey: ${STEAM_API_KEY}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "VartaStore"
      Jwt__Audience: "VartaClient"
      
      # == УНІВЕРСАЛЬНА ЗМІННА ==
      AppUrl: ${PUBLIC_URL}
      AllowedOrigins__0: ${PUBLIC_URL}
      
      # Donatik Configuration
      Donatik__Token: ${DONATIK_TOKEN}
      Donatik__UseMock: "false" 
      
      # Game API Key for DayZ mod integration
      GameApi__Key: ${GAME_API_KEY}
      
      # Location to save images inside the container
      Storage__ImagesPath: "/app/images/products"

    volumes:
      - product_images:/app/images/products

  client:
    build:
      context: .
      dockerfile: Varta.Store.Client/Dockerfile
    container_name: varta_client
    restart: always
    ports:
      # Локально: 7120
      # На проді поміняєте на "80:80" або "443:443"
      - "7120:80"
    depends_on:
      - api
    volumes:
      - product_images:/usr/share/nginx/html/images/products

volumes:
  postgres_data:
  product_images: